# Site settings
# source ~/.rvm/scripts/rvm
title: Ramon Barros
description: Developer
url: http://ramon-barros.com
baseurl: /
google_analytics: UA-32626396-1
google_site_verification: guyNAJizf4Z_4vd0tVhQt6uEwQcBcUVp3J7ATwGeMoY

author:
  name: Ramon Barros
  email: contato@ramon-barros.com
  twitter_username: ramonbarros_
  github_username:  rbarros
  linkedin_username:  ramonbarros

# Build settings
destination: _site
paginate: 10
paginate_path: /page:num/
permalink: /:categories/:year/:month/:day/:title.html
markdown: kramdown

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  syntax_highlighter: rouge

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
gems: ['jekyll-paginate']
